name: Auto no merge
on: pull_request

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          intervalSeconds: 1
          timeoutSeconds: 60
          ignoreLabels: notMergable
